import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/SessionProvider";
import QueryProvider from "@/components/QueryProvider";
import { Toaster } from "@/components/ui/sonner";
import { SidebarProvider } from "@/components/ui/sidebar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <QueryProvider>
        <SidebarProvider>
          <html lang="en" className="h-full">
            <body
              className={`${inter.variable} antialiased flex bg-gradient-to-br from-slate-950 via-indigo-950 to-purple-950 text-white min-h-screen h-full bg-fixed`}
            >
              <main className="flex-1 w-full">
                {children}
              </main>
              <Toaster />
            </body>
          </html>
        </SidebarProvider>
      </QueryProvider>
    </SessionProvider>
  );
}
